// Fetch whole chapters from Sefaria (Miqra according to the Masorah — nikud
// AND ta'amei hamikra) and write them as TypeScript verse files under
// content/tasks/verses/. The Name is written ה׳ as everywhere on the site,
// keeping its taam so the verse division stays readable.
//
//   node scripts/fetch-verses.mjs Leviticus.8 Leviticus.9 II_Samuel.11 ...
//
// Output: content/tasks/verses/<book>-<chapter>.ts exporting the verses and
// a one-based inclusive slice helper, e.g. LEVITICUS_8 / verses(1, 13).
import { writeFileSync, mkdirSync } from "node:fs";
import { join } from "node:path";

const OUT = join(process.cwd(), "content", "tasks", "verses");
mkdirSync(OUT, { recursive: true });

const HEB_BOOK = { Leviticus: "ויקרא", II_Samuel: "שמואל ב׳" };

// Hebrew verse numbers: 15 → טו, 16 → טז, no gershayim (plain, like the site)
function hebNum(n) {
  const ones = ["", "א", "ב", "ג", "ד", "ה", "ו", "ז", "ח", "ט"];
  const tens = ["", "י", "כ", "ל", "מ", "נ", "ס", "ע", "פ", "צ"];
  if (n === 15) return "טו";
  if (n === 16) return "טז";
  return tens[Math.floor(n / 10)] + ones[n % 10];
}

// the Name → ה + its taamim + ׳  (prefixes like לַ / בַּ / וַ stay)
const NAME = /י[\u0591-\u05c2\u05c4-\u05c7]*ה[\u0591-\u05c2\u05c4-\u05c7]*ו[\u0591-\u05c2\u05c4-\u05c7]*ה[\u0591-\u05c2\u05c4-\u05c7]*/g; // never swallow sof pasuk (U+05C3)
function hideName(text) {
  return text.replace(NAME, (m) => {
    const taamim = [...m].filter((c) => /[֑-֮]/.test(c)).join("");
    return "ה" + taamim + "׳";
  });
}
function clean(html) {
  return hideName(
    html
      .replace(/&thinsp;/g, " ")
      .replace(/&nbsp;/g, " ")
      .replace(/<[^>]+>/g, "")
      .replace(/\s*\{[ספ]\}/g, "")
      .replace(/\s+/g, " ")
      .trim()
  );
}

for (const ref of process.argv.slice(2)) {
  const [book, chapter] = ref.split(".");
  const url = `https://www.sefaria.org/api/v3/texts/${ref}?version=hebrew|Miqra_according_to_the_Masorah`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`${ref}: HTTP ${res.status}`);
  const json = await res.json();
  const text = json.versions?.[0]?.text;
  if (!Array.isArray(text)) throw new Error(`${ref}: no text`);
  const verses = text.map((t, i) => ({ num: hebNum(i + 1), text: clean(String(t)) }));
  const constName = `${book.toUpperCase().replace(/[^A-Z0-9]/g, "_")}_${chapter}`;
  const heb = HEB_BOOK[book] ?? book;
  const file = join(OUT, `${book.toLowerCase().replace(/[^a-z0-9]/g, "-")}-${String(chapter).padStart(2, "0")}.ts`);
  const lines = [
    `import type { PassageVerse } from "../types";`,
    ``,
    `// ${heb} פרק ${hebNum(Number(chapter))} — with nikud and ta'amei hamikra. Text: Miqra`,
    `// according to the Masorah (Sefaria). The Name is written ה׳ as everywhere on`,
    `// the site, keeping its taam. Generated by scripts/fetch-verses.mjs — do not`,
    `// hand-edit; re-run the script instead.`,
    `export const ${constName}: PassageVerse[] = [`,
    ...verses.map((v) => `  { num: ${JSON.stringify(v.num)}, text: ${JSON.stringify(v.text)} },`),
    `];`,
    ``,
    `// one-based inclusive slice: verses(1, 5) → א–ה`,
    `export function verses(from: number, to: number): PassageVerse[] {`,
    `  return ${constName}.slice(from - 1, to);`,
    `}`,
    ``,
  ];
  writeFileSync(file, lines.join("\n"), "utf8");
  console.log(`${ref}: ${verses.length} verses → ${file}`);
}
